chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

chat/models.py
from django.db import models

class Room(models.Model):
	
	# Room title
	title = models.CharField(max_length=255)
	
	def __str__(self):
		return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
	pass
	
	def __str__(self):
		return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
	
	class Meta:
		model = CustomUser
		fields = ('username', 'email')
		
class CustomUserChangeForm(UserChangeForm):
	
	class Meta:
		model = CustomUser
		fields = ('username', 'email')

chat/views.py
from django.shortcuts import render, redirect
from django.contrib.sessions.models import Session


from .models import Room

def index(request):
	room_list = Room.objects.order_by('title')
	return render(request, 'chat/index.html', {'room_list': room_list})

def room(request, room_name):
	return render(request, 'chat/room.html', {'room_name': room_name})

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'signup.html'

chat/templates/chat/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'chat/style.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>
<body>
    <div>
        <! -- user is a context processor -- !>
      <h1 class="text-center">Hi {{ request.user.username }}! What chat room would you like to enter?<br></h1>
      <input id="room-name-input" class="form-control" type="text"><br>
    </div>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
    <div>
      <h4>Select a Popular Room</h4>
      {% for room in room_list %}
        <div>
            <p><a href="{% url 'chat:room' room.title %}">{{ room.title }}</a></p>
        </div>
      {% endfor %}
    </div>
</body>
</html>

chat/templates/chat/room.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <header>
    <p class="text-center">{{ room_name }} Chat Room</p>
    </header>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'chat/style.css' %}">
</head>
<body>
    <textarea id="chat-log" class="form-control" cols="100" rows="20" readonly></textarea><br>
    <!--Typing Notifier-->
    <div class="typingNotifier" style="height:30px"><p id="keyboarding"></p></div>
    <input id="chat-message-input" class="form-control" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    
    {{ room_name|json_script:"room-name" }}
    <script>
        var roomName = JSON.parse(document.getElementById('room-name').textContent);
        var chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );
        
        // When a message is received from the server
        chatSocket.onmessage = function(e) {
            console.log('dfsdf');
            // Decode the JSON
            var data = JSON.parse(e.data);
            console.log(data);
            // If chat consumer joins or leaves the channel, a broadcast message sends
            let msg;
            if (data.action === 'join' || data.action === 'leave') {
                msg = data.username + data.message + '\n';
                document.querySelector('#chat-log').value += msg;
            }
            
            else if (data.action === 'keyboarding' && data.event === 'sentMsg') {
                msg = data.username + ': ' + data.message + '\n';
                document.querySelector('#chat-log').value += msg;
            }
        
            // Typing notification event
            if (data.action) {
                //console.log('outer if notification event')
                var typingElem = document.getElementById('keyboarding');
                if (data.action === 'keyboarding') {
                    typingElem.innerHTML = data.username + ' is typing...';
                    // set css of typingElem invi : false
                    //console.log('inner if notification event')
                }
                else if (data.action === 'stopKeyboarding') {
                    typingElem.innerHTML = ' ';
                    //console.log('inner else if notification event')
                } 
            }
        };
        
        var input = document.querySelector('#chat-message-input');
        var submitBtn = document.querySelector('#chat-message-submit');
        
        input.focus();
        input.onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                submitBtn.click();
            }
        }
        
        // typing timer handling
        var typingTimer;
        var timer;
        input.onkeydown = function(e) {
            if (typingTimer) {
                clearTimeout(typingTimer);
                
                typingTimer = setTimeout(function() {
                    chatSocket.send(JSON.stringify({ // to consumer.py as the content
                        'type': 'stopKeyboarding',
                        //'message': 'stopped typing',
                    }));
                }, 1000)
                
                if (timer) clearTimeout(timer)
                timer = setTimeout(function() {
                    clearTimeout(typingTimer);
                    typingTimer = undefined;
                }, 1200)
                
                return;
            };
            
            chatSocket.send(JSON.stringify( // to consumer.py as the content
            {
                'type': 'keyboarding',
                //'message': 'is typing',
            }));
            
            typingTimer = setTimeout(function() {
                chatSocket.send(JSON.stringify( // to consumer.py as the content
                {
                    'type': 'stopKeyboarding',
                    //'message': 'stopped typing',
                }));
            }, 3000)
            
        };

        submitBtn.onclick = function(e) {
            var messageInputDom = document.querySelector('#chat-message-input');
            var message = messageInputDom.value;
            chatSocket.send(JSON.stringify({ // to consumer.py
                'command': 'send',
                'message': message,
            }));
            messageInputDom.value = '';
        };
        
        // Debugging info for web console
        chatSocket.onopen = function(e) {
            console.log('Connected to chat socket');
        };
        
        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
    </script>
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'chat/homepage.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div>
  {% if user.is_authenticated %}
    <h2>Hi {{ user.username }}!</h2>
    <button type="submit"><a href="{% url 'logout' %}" class="top-menu">Log Out</a></button>
  <header>
  {% endif %}
</div>
<div>
  {% if user.is_authenticated %}
  <h4><a href="{% url 'chat:index' %}">Chat</a> | <a href="{% url 'polls:index' %}">Polls</a> | <a href="{% url 'index' %}">Blog</a></h4>
  {% else %}
  <h4><a href="{% url 'polls:index' %}">Polls</a> | <a href="{% url 'index' %}">Blog</a></h4>
  {% endif %}
</div>
<div>
  <p>Please login or signup to access all website features.</p>
  <div>
    <button type="submit"><a href="{% url 'login' %}">Log In</a></button> |
    <button type="submit"><a href="{% url 'users:signup' %}">Sign Up</a></button>
  </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}